### ISSUE TITLE
2.4. Create script that generates Table 1

### ISSUE THREAD

**Issue by Fernando-Urbano** [Fernando-Urbano/monash-time-series-replication#13]

**Comment by shreyjain-uchicago** [comment]
Edited the data_loader file to generate table 1 (in my working branch).
Future tasks:
- Include this in the dodo file to make it compute based on doit command
- Include qualitative comments on few datasets

**Comment by Fernando-Urbano** [comment]
Great!!

**Comment by shreyjain-uchicago** [comment]
I included it in Dodo file as well and it works.
However keep this in mind, it takes about 7-10 mins to generate table 1 for all 57 datasets downloaded.

**Comment by Fernando-Urbano** [comment]
Great!
Does that include the time to download the datasets?

**Comment by Fernando-Urbano** [comment]
- everything AMAZING!

**Comment by Fernando-Urbano** [comment]
had to redo it because it was not right

**Comment by Fernando-Urbano** [comment]
had to redo it because the table was different from the result of the paper
